version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=shivam
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=Vipin
    command: >
      bash -c "sleep 10 &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Vipin
      MYSQL_DATABASE: shivam
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pVipin"]
      timeout: 20s
      retries: 10
      interval: 5s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: